### PR TITLE
filenames should match structure names

### PR DESCRIPTION
**Pull request by RussTedrake**
lcm-gen generates the output filenames based on the name of the structure (in the lcm code), not based on the name of the files.  when these don't match, it's a pain -- especially for bazel, which is trying to explicitly reason about the generated outputs -- and I think it's a defect.  

For the same reason, I think this should not break downstream users.  

I needed to make this change to make bazel builds work correctly; there is a more painful/brittle work-around that i can do if necessary.

@patmarion, @wxmerkt -- for your consideration.

### CODE REVIEW

**Comment by patmarion** [comment]
this file rename seems fine to me, but, it seems like there is still nothing enforcing the rule that filenames should match the type name declared in the .lcm file, so that still seems like a tricky point for build systems to manage.

by the way, shouldn't drake be using https://github.com/openhumanoids/bot_core_lcmtypes and this PR should be against that repo?

**Comment by RussTedrake** [comment]
yes.  was surprised to see the local reference in master.  @mwoehlke-kitware -- perhaps you can make this happen after this merge?

**Comment by mwoehlke-kitware** [comment]
> it seems like there is still nothing enforcing the rule that filenames should match the type name declared in the .lcm file

There is not. Moreover, you are assuming that a `.lcm` contains exactly one type definition; this is also not required. If you feel this is a defect, I advise taking it [upstream](https://github.com/lcm-proj/lcm). I suspect, however, that it is an intentional design decision that will not be changed.

CMake handles both quirks just fine. (Note that it does so by inspecting the input files. That step is necessary — if the build system needs to know a priori the output file names (which most do) — to not impose artificial limitations on what `.lcm` files the build system will handle compared to what `lcm-gen` will handle.)

**Comment by RussTedrake** [comment]
can you point me to the cmake logic that checks the input files.  i searched for it quickly, but didn't see it?

an even better solution would be to write the input file inspector into drake-distro/tools/lcm.bzl (shouldn't be too hard).  are you willing to take a shot at that?

cc @jwnimmer-tri .

**Comment by mwoehlke-kitware** [comment]
> by the way, shouldn't [...] this PR should be against that repo?

I agree; this sort of change is something that have buy-in from upstream, or else we should to commit to maintaining a proper fork. Please re-submit this PR against https://github.com/openhumanoids/bot_core_lcmtypes.

**Comment by RussTedrake** [comment]
i'd also like a consensus on where the generated files should land.  it seems like we have some code in drake referencing them via `#include <lcmtypes/bot_core/pointclout_t.hpp>` and others using `#include <bot_core/pointcloud_t.hpp>`.

**Comment by mwoehlke-kitware** [comment]
> can you point me to the cmake logic that checks the input files?

https://github.com/lcm-proj/lcm/blob/master/lcm-cmake/lcmUtilities.cmake#L251-L273

You basically need to do two things: scan for `package` directives, which will affect the output file paths, and scan for `struct`/`enum` directives, which trigger creation of output files (one set per such directive).

> i'd also like a consensus on where the generated files should land.  it seems like we have some code in drake referencing them via `#include <lcmtypes/bot_core/pointclout_t.hpp>` and others using `#include <bot_core/pointcloud_t.hpp>`.

As of RobotLocomotion/drake#3550, a) the consensus was to omit `lcmtypes/`, and b) all includes had (in theory) been adjusted accordingly. People must be adding new ones not following that convention?

**Comment by RussTedrake** [comment]
agree on all points.  in fact, you might be right -- the code that was using the include with `lcmtypes `was something that I was porting from a fork.  omiting `lcmtypes` it is.

**Pull request closed without merging**
